#!/bin/bash

cat << EOF | sudo tee /Library/LaunchAgents/com.github.primenotify.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>com.github.primenotify</string>
<key>ProgramArguments</key>
<array>
  <string>$HOME/primenotify/checker</string>
  <string>--path=$HOME/primenotify/config.json</string>
</array>
<key>StartInterval</key>
<integer>600</integer>
</dict>
</plist>
EOF
